### ISSUE TITLE
Create PR by Adding Details

### ISSUE THREAD

**Issue by mmuhamadamirzaidi** [mmuhamadamirzaidi/Hacktoberfest#1]
Create your PR by adding your details into the table such as name, position, GitHub, and LinkedIn link, also country. Please give a **STAR** for this repository :D. Any PR that doesn't follow the format will not be counts. Thanks, go fork, and create the PR now!

**Comment by nitinshukla413** [comment]
can you please assign this issue to me

**Comment by mmuhamadamirzaidi** [comment]
Sure @nitinshukla413 , just follow the Contributing steps.

**Comment by mmuhamadamirzaidi** [comment]
**Don't forget to give a STAR for this repository :D**

**Comment by ays14** [comment]
Hi @mmuhamadamirzaidi 
I think I can take it up as well, right?

**Comment by mmuhamadamirzaidi** [comment]
Sure! Go on @ays14 :D

**Comment by ays14** [comment]
> Sure! Go on @ays14 :D

Thanks @mmuhamadamirzaidi

**Comment by ajay272191** [comment]
Hi @mmuhamadamirzaidi  i have created a pull request please have a visit Thank you.

**Comment by mmuhamadamirzaidi** [comment]
Great work @ajay272191 . Don't forget to START this project. Thanks :D

**Comment by Nightsmore** [comment]
Hey, created a PR.  Take a look?

**Comment by arham09** [comment]
hello @mmuhamadamirzaidi, created a PR, please take a look

**Comment by mmuhamadamirzaidi** [comment]
> Hey, created a PR. Take a look?

I have merge your details @Nightsmore . Great works!

**Comment by mmuhamadamirzaidi** [comment]
> hello @mmuhamadamirzaidi, created a PR, please take a look

I have merge your details @arham09 . Great works!

**Comment by agungbudimiantoro** [comment]
hello. why i got Ineligible Repository in hacktoberfest.digitalocean website?

**Comment by kalpanaT-05** [comment]
@mmuhamadamirzaidi can i contribute on this project?

**Comment by mmuhamadamirzaidi** [comment]
Sure @kalpanaT-05 . Just add your details and create a PR :D

**Comment by mmuhamadamirzaidi** [comment]
> hello. why i got Ineligible Repository in hacktoberfest.digitalocean website?

Im not sure @agungbudimiantoro . Maybe you can check their FAQs here [https://hacktoberfest.digitalocean.com/faq](https://hacktoberfest.digitalocean.com/faq)

**Comment by kalpanaT-05** [comment]
> Sure @kalpanaT-05 . Just add your details and create a PR :D

sure i will do it, thank you

**Comment by kalpanaT-05** [comment]
@mmuhamadamirzaidi i have added the details and pulled a request do check and merge it

**Comment by mmuhamadamirzaidi** [comment]
> @mmuhamadamirzaidi i have added the details and pulled a request do check and merge it

Already merge. Great works! :D

**Comment by saurabhhere** [comment]
#49 
Have a look on this @mmuhamadamirzaidi

**Comment by mmuhamadamirzaidi** [comment]
Will check the PR and add the label hacktoberfest-accepted for all successful PR merge. Have fun!

**Comment by mmuhamadamirzaidi** [comment]
@shubhamcodez  can you please check any conflict before merging the PR? Thanks

**Comment by shubhamcodez** [comment]
@mmuhamadamirzaidi  Hey, I check for conflicts and resolve them before merging the PRs, was there any issue ? I'm sorry for that 😓

**Comment by shweta-laha** [comment]
hey! I would like to contribute if you want :)

**Comment by I3han** [comment]
Hey there, Can you check my PR @mmuhamadamirzaidi . Have nice day, Thank you

**Comment by shubhamcodez** [comment]
> hey! I would like to contribute if you want :)

Sure , just create a PR

**Comment by ripperkumar** [comment]
i want to  work on it can i?

**Comment by kerianne16** [comment]
hi i'd like to contribute to this well :)

**Comment by yusril23** [comment]
Hi, I done create my PR @mmuhamadamirzaidi please check my contribute #72 . Thank you

**Comment by Illusion47586** [comment]
hey @mmuhamadamirzaidi , please look into PR #71 . Thanks!

**Comment by mmuhamadamirzaidi** [comment]
> i want to work on it can i?

Sure! Go ahead @ripperkumar :D

**Comment by mmuhamadamirzaidi** [comment]
> hi i'd like to contribute to this well :)

Yes, sure @kerianne16 :D

**Comment by mmuhamadamirzaidi** [comment]
> Hi, I done create my PR @mmuhamadamirzaidi please check my contribute #72 . Thank you

Merged already! Don't forget to put a start on this repository :D

**Comment by mmuhamadamirzaidi** [comment]
> hey @mmuhamadamirzaidi , please look into PR #71 . Thanks!

Already merged :D . Don't forget to give a **STAR**

**Comment by himanshubobade** [comment]
@mmuhamadamirzaidi Please accept my pull request

**Comment by himanshubobade** [comment]
@mmuhamadamirzaidi please take a look at my PR

**Comment by mmuhamadamirzaidi** [comment]
> @mmuhamadamirzaidi please take a look at my PR

Done :D

**Comment by mmuhamadamirzaidi** [comment]
Thank you everyone for the supports and contributions to this repository. Such a great experience to collab with all of you. See you guys next year :D. Once again, big thanks!
