### ISSUE TITLE
Readme Enhancement

### ISSUE THREAD

**Issue by shubhamcodez** [mmuhamadamirzaidi/Hacktoberfest#2]
Readme is difficult to read and follow.

for eg:

After forking 
You have mentioned this repo itself to be cloned but contributer will clone his own forked repo.

     Instead of : >  git clone https://github.com/mmuhamadamirzaidi/Hacktoberfest.git
                        > git clone https://github.com/<your name>/Hacktoberfest.git
                         Note : <your name> replaced by your Github username.

**Comment by mmuhamadamirzaidi** [comment]
Thanks and sorry for the issues. You can contribute by fixing the README file @shubhamcodez

**Comment by mmuhamadamirzaidi** [comment]
Done fix. But if want to enhance the README file, just go on @shubhamcodez :D

**Comment by shubhamcodez** [comment]
I have made some changes on the readme formatting.
Please take a look sir .

**Comment by mmuhamadamirzaidi** [comment]
Sure. You can try to make changes with the latest README.md file I fix just now. Thanks @shubhamcodez

**Comment by shubhamcodez** [comment]
I have made a PR but it has some conflict.
can you tell me how to resolve it?

**Comment by mmuhamadamirzaidi** [comment]
Let me check

**Comment by mmuhamadamirzaidi** [comment]
Solved! Thanks @shubhamcodez . Amazing work! :D

**Comment by shubhamcodez** [comment]
Hey, I propose people should be asked to make more meaningful contributions. 
Like adding a backend support or a login page

**Comment by mmuhamadamirzaidi** [comment]
I create this repository so that all developers from all levels can contribute and play around with Git @shubhamcodez :D. Maybe next year, I will create something more challenging. Thanks for the recommendations 👍
