### ISSUE TITLE
Add hacktoberfest to project topic

### ISSUE THREAD

**Issue by NoahBlaaa15** [mmuhamadamirzaidi/Hacktoberfest#41]
To count for Hacktoberfest, the topic Hacktoberfest needs to be added to the project.

**Comment by mmuhamadamirzaidi** [comment]
Where need to add the topic Hacktoberfest, @NoahBlaaa15 ? You can change and create a PR for that. Thanks.

**Comment by NoahBlaaa15** [comment]
The topic isn't changed in any files, you have to edit the about field on the repository main page, there is an extra text box where you can enter topics.

**Comment by mmuhamadamirzaidi** [comment]
Done adding the topics. Thanks @NoahBlaaa15 👍
